twitter:
  outputs:
    default:
      dataset: default
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GOOGLE_PROJECT_ID') }}"
      threads: 4
      type: bigquery
  target: default